// Single source of truth for the timestamp format written to every synced
// column (created_at / updated_at / deleted_at). Millisecond precision in the
// same space-separated shape as the old `datetime('now')` (D3) — sorts
// identically to legacy second-precision rows, just with `.fff` accuracy.
// Interpolated into SQL strings here and in the query layer so the format can
// never drift between code paths.
export const TS_NOW = "strftime('%Y-%m-%d %H:%M:%f', 'now')";

// Client-side UUIDv4 generated by SQLite's built-in PRNG (no JS dependency).
// `randomblob` is re-evaluated per row, so this yields a distinct id for every
// inserted/backfilled row. Used as the cross-device sync key (D1).
export const UUID4_SQL =
  "lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || " +
  "substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || " +
  "substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))";

// The 9th synced table (Slice F). Image binaries live in S3; this row carries
// only the cross-device `s3_key` reference plus the sync columns. `local_uri` is
// device-local (the on-disk path the picker/download wrote to) and is NEVER put
// on the wire — display resolves an image's on-disk file by joining the `uuid`
// stamped into notes.content against this table's `local_uri`. Created fresh
// (with all sync columns) via SCHEMA_SQL on new installs and via the v2→v3
// migration on existing ones, so — unlike the other tables — its unique uuid
// index is safe to declare here: the column always exists at creation time.
export const NOTE_IMAGES_SQL = `
  CREATE TABLE IF NOT EXISTS note_images (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid       TEXT,
    note_id    INTEGER NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
    s3_key     TEXT,
    local_uri  TEXT,
    created_at TEXT NOT NULL DEFAULT (${TS_NOW}),
    updated_at TEXT NOT NULL DEFAULT (${TS_NOW}),
    deleted_at TEXT,
    -- Device-local, never synced: set to 1 when an image exceeds MAX_IMAGE_BYTES
    -- and is permanently skipped for cloud upload (keeps it off the retry loop).
    upload_skipped_too_large INTEGER NOT NULL DEFAULT 0
  );

  CREATE UNIQUE INDEX IF NOT EXISTS idx_note_images_uuid    ON note_images(uuid);
  CREATE INDEX        IF NOT EXISTS idx_note_images_note_id ON note_images(note_id);
`;

export const SCHEMA_SQL = `
  CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS stage_definitions (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT NOT NULL,
    color       TEXT NOT NULL,
    order_index INTEGER NOT NULL DEFAULT 0
  );

  CREATE TABLE IF NOT EXISTS task_types (
    id    INTEGER PRIMARY KEY AUTOINCREMENT,
    name  TEXT NOT NULL,
    color TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS locations (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid        TEXT,
    name        TEXT NOT NULL,
    order_index INTEGER NOT NULL DEFAULT 0,
    updated_at  TEXT NOT NULL DEFAULT (${TS_NOW}),
    deleted_at  TEXT
  );

  CREATE TABLE IF NOT EXISTS gardens (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid              TEXT,
    location_id       INTEGER NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    name              TEXT NOT NULL,
    record_type       TEXT NOT NULL DEFAULT 'plant',
    order_index       INTEGER NOT NULL DEFAULT 0,
    updated_at        TEXT NOT NULL DEFAULT (${TS_NOW}),
    deleted_at        TEXT
  );

  CREATE TABLE IF NOT EXISTS sections (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid        TEXT,
    garden_id   INTEGER NOT NULL REFERENCES gardens(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    order_index INTEGER NOT NULL DEFAULT 0,
    updated_at  TEXT NOT NULL DEFAULT (${TS_NOW}),
    deleted_at  TEXT
  );

  CREATE TABLE IF NOT EXISTS crop_instances (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid        TEXT,
    section_id  INTEGER NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    plant_count INTEGER NOT NULL DEFAULT 1 CHECK (plant_count > 0),
    start_date  TEXT NOT NULL,
    record_type TEXT NOT NULL DEFAULT 'plant',
    archived    INTEGER NOT NULL DEFAULT 0,
    notes       TEXT,
    created_at  TEXT NOT NULL DEFAULT (${TS_NOW}),
    updated_at  TEXT NOT NULL DEFAULT (${TS_NOW}),
    deleted_at  TEXT
  );

  CREATE TABLE IF NOT EXISTS crop_stages (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                TEXT,
    crop_instance_id    INTEGER NOT NULL REFERENCES crop_instances(id) ON DELETE CASCADE,
    stage_definition_id INTEGER NOT NULL REFERENCES stage_definitions(id),
    duration_weeks      INTEGER NOT NULL CHECK (duration_weeks > 0),
    order_index         INTEGER NOT NULL DEFAULT 0,
    updated_at          TEXT NOT NULL DEFAULT (${TS_NOW}),
    deleted_at          TEXT
  );

  CREATE TABLE IF NOT EXISTS tasks (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid               TEXT,
    crop_instance_id   INTEGER NOT NULL REFERENCES crop_instances(id) ON DELETE CASCADE,
    task_type_id       INTEGER NOT NULL REFERENCES task_types(id),
    day_of_week        INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    frequency_weeks    INTEGER NOT NULL DEFAULT 1 CHECK (frequency_weeks > 0),
    start_offset_weeks INTEGER NOT NULL DEFAULT 0 CHECK (start_offset_weeks >= 0),
    created_at         TEXT NOT NULL DEFAULT (${TS_NOW}),
    updated_at         TEXT NOT NULL DEFAULT (${TS_NOW}),
    deleted_at         TEXT
  );

  CREATE TABLE IF NOT EXISTS task_completions (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid           TEXT,
    task_id        INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    completed_date TEXT NOT NULL,
    updated_at     TEXT NOT NULL DEFAULT (${TS_NOW}),
    deleted_at     TEXT,
    UNIQUE(task_id, completed_date)
  );

  CREATE TABLE IF NOT EXISTS notes (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid             TEXT,
    entity_type      TEXT NOT NULL,
    entity_id        INTEGER,
    week_date        TEXT,
    crop_instance_id INTEGER REFERENCES crop_instances(id) ON DELETE CASCADE,
    content          TEXT NOT NULL,
    created_at       TEXT NOT NULL DEFAULT (${TS_NOW}),
    updated_at       TEXT NOT NULL DEFAULT (${TS_NOW}),
    deleted_at       TEXT
  );

  ${NOTE_IMAGES_SQL}

  CREATE INDEX IF NOT EXISTS idx_crop_instances_section_id  ON crop_instances(section_id);
  CREATE INDEX IF NOT EXISTS idx_crop_instances_archived     ON crop_instances(archived);
  CREATE INDEX IF NOT EXISTS idx_tasks_crop_instance_id      ON tasks(crop_instance_id);
  CREATE INDEX IF NOT EXISTS idx_task_completions_task_id    ON task_completions(task_id);
  CREATE INDEX IF NOT EXISTS idx_notes_crop_instance_id      ON notes(crop_instance_id);

  -- At most one week_cell note per (crop, week). Partial index lets SQLite
  -- enforce uniqueness only for the week-cell shape, where both columns are
  -- guaranteed non-null, and serves as the conflict target for upsertNote.
  CREATE UNIQUE INDEX IF NOT EXISTS idx_notes_week_cell_unique
    ON notes(entity_type, crop_instance_id, week_date)
    WHERE entity_type = 'week_cell' AND crop_instance_id IS NOT NULL AND week_date IS NOT NULL;

  -- NOTE: the per-table unique uuid indexes (idx_<table>_uuid) are intentionally
  -- NOT created here. This block runs via CREATE TABLE IF NOT EXISTS, which is a
  -- no-op on an existing (pre-uuid) DB, so the uuid column may not exist yet when
  -- this SQL runs. runMigrations creates those indexes after ALTER-adding uuid.
`;
